version: '3'
services:

  mongodb:
    # Document database used by EMG API mostly for assembly contigs and annotations on them
    image: mongo:4.0.17
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mysql:
    # Relational databased used by EMG API, managed by Django.
    # For most dev purposes this isn't needed thanks to SQLite.
    # Use this service for testing mysql-specific things.
    image: mysql:5.6
    profiles:
      - mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=emg
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    # Redis used for sourmash (genome search) job queue.
    # NOT used for API caching at this time.
    profiles:
      - sourmash
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  api:
    # EMG API built on Django.
    build:
      context: ./emgapi/
      dockerfile: docker/lite.Dockerfile
    volumes:
      - ./emgapi/:/opt/emgapi
      - ./ebi-metagenomics-client/ci/:/opt/ci
      - ./ebi-metagenomics-client/ci/emg_api_datafiles/results/:/opt/emgapi/results
      - sourmash-data:/opt/sourmash
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - PYTHONUNBUFFERED=0
      - EMG_CONFIG=${EMG_CONFIG}  # must be specified as env var to `docker compose up`
      - BACKLOG_CONFIG=config/backlog-local.yml

  sourmash-queue:
    # Job runner for the sourmash-based genome search microservice.
    profiles:
      - sourmash
    build:
      context: ./sourmash-queue/
      dockerfile: Dockerfile
    volumes:
      - ./sourmash-queue/:/opt/app
      - sourmash-data:/opt/sourmash
      - type: bind
        source: ./sourmash-queue/settings-local.py
        target: /opt/app/settings.py
    depends_on:
      - redis

  flower:
    # Dashboard for viewing the state of the sourmash microservice job queue.
    profiles:
      - sourmash
    build:
      context: ./sourmash-queue/
      dockerfile: Dockerfile
    command: celery -A tasks flower --loglevel=INFO
    volumes:
      - ./sourmash-queue/:/opt/app
      - ./sourmash-queue/settings-local.py:/opt/app/settings.py
      - sourmash-data:/opt/sourmash
    ports:
      - "5555:5555"  # for flower dashboard, browse to 127.0.0.1:5555
    depends_on:
      - redis

volumes:
  redis-data:
  sourmash-data:
  mysql-data:
  mongo-data:
