version: '3'
services:
  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=emg
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  api-lite:
    environment:
      - PYTHONUNBUFFERED=0
      - EMG_CONFIG=config/local-mysql.yml
      - BACKLOG_CONFIG=config/backlog-local.yml

volumes:
   mysql-data: