version: '3'
services:

  mongodb-lite:
    image: mongo:3.4
    ports:
      - "27017:27017"

  api-lite:
    build:
      context: ./emgapi/
      dockerfile: docker/lite.Dockerfile
    volumes:
      - ./emgapi/:/opt/emgapi
      - ./ebi-metagenomics-client/ci/:/opt/ci
      - ./ebi-metagenomics-client/ci/emg_api_datafiles/results/:/opt/emgapi/results
    ports:
      - "8000:8000"
    links:
      - mongodb-lite
    environment:
      - PYTHONUNBUFFERED=0
      - EMG_CONFIG=config/local-lite.yml
      - BACKLOG_CONFIG=config/backlog-local.yml