version: '3'
services:

  mongodb-lite:
    image: mongo:3.4
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  api-lite:
    build:
      context: ./emgapi/
      dockerfile: docker/lite.Dockerfile
    volumes:
      - ./emgapi/:/opt/emgapi
      - ./ebi-metagenomics-client/ci/:/opt/ci
      - ./ebi-metagenomics-client/ci/emg_api_datafiles/results/:/opt/emgapi/results
      - sourmash-data:/opt/sourmash
    ports:
      - "8000:8000"
    links:
      - mongodb-lite
      - redis
    environment:
      - PYTHONUNBUFFERED=0
      - EMG_CONFIG=config/local-lite.yml
      - BACKLOG_CONFIG=config/backlog-local.yml

  sourmash-queue:
    build:
      context: ./sourmash-queue/
      dockerfile: Dockerfile
    volumes:
      - ./sourmash-queue/:/opt/app
      - ./sourmash-queue/settings-local.py:/opt/app/settings.py
      - sourmash-data:/opt/sourmash
    ports:
      - "5555:5555"  # for flower dashboard, browse to 127.0.0.1:5555
    links:
      - redis

#  api-tests:
#    build:
#      context: ./emgapi/
#      dockerfile: docker/tests.Dockerfile
#    volumes:
#      - ./emgapi/:/opt/emgapi
#      - ./ebi-metagenomics-client/ci/:/opt/ci
#      - ./ebi-metagenomics-client/ci/emg_api_datafiles/results/:/opt/emgapi/results
#    links:
#      - mongodb-lite
#    environment:
#      - PYTHONUNBUFFERED=0
#      - EMG_CONFIG=config/local-tests.yml

volumes:
  redis-data:
  sourmash-data:
